### ISSUE TITLE
Submit button classes

### ISSUE THREAD

**Issue by eclectic-coding** [king601/devise-bootstrapped#10]
@afomera After using on a recent project (bootstrap4) I noticed a problem with the form submit buttons. The below code is from `devise/registrations/new.html.erb`:

```
<div class="form-group">
        <%= f.submit "Sign up", class: "btn btn-primary btn-block btn-lg" %>
</div>
```
This results in a light background button with light text, which changes to `btn-primary` only on hover. I thing the `form-group` should be `form-control`. 

Thanks for a great product.

**Comment by afomera** [comment]
@eclectic-coding would you mind checking if you have a scaffolds css file? That can sometimes interfere with the bootstrap styles.

Also if you could provide a screenshot that'd be great!

**Comment by eclectic-coding** [comment]
Sorry, did a fresh app install and it seems to be working now. Not sure what was going on yesterday, but okay now. 

Have a good day.
