### ISSUE TITLE
Deprecation issue: devise_error_messages will no longer work after next major release

### ISSUE THREAD

**Issue by rodrigoargumedo** [king601/devise-bootstrapped#5]
Hey, I was fiddling with the devise-bootstrapped gem and came across with this deprecation warning in my Rails server output (as of v4.6.2) after generating the views:

`DEPRECATION WARNING: [Devise] "DeviseHelper.devise_error_messages!" is deprecated and it will be removed in the next major version.`

I guess I have to `render partial: 'devise/shared/error_messages'` for the error messages from this point on.

**Comment by afomera** [comment]
Hey @rodrigoargumedo thanks for submitting this ticket. Is this something you'd like to try and fix in the views for the gem?

**Comment by rodrigoargumedo** [comment]
Absolutely! I will just need to get the views regenerated and modify some of them to use bootstrap.

________________________________

**Comment by afomera** [comment]
Great! Let me know if I can be of assistance :)

**Comment by afomera** [comment]
Merged this PR :) Thanks @rodrigoargumedo, I'd recommend using the gem from github!
